name: 柠柠檬的博客
author: eytb2
#baseurl: /liangren.com
keywords: java,github,git,jekyll,gollum,jquery,flash
description: 
github: https://github.com/eytb2
email: eby0620@gmail.com


encoding: utf-8
#highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
